# Autogenerated wrapper script for CUTEst_jll for aarch64-linux-gnu-libgfortran5
export libcutest_double, libcutest_double_a, libcutest_single, libcutest_single_a

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("CUTEst")
JLLWrappers.@declare_library_product(libcutest_double, "libcutest_double.so")
JLLWrappers.@declare_file_product(libcutest_double_a)
JLLWrappers.@declare_library_product(libcutest_single, "libcutest_single.so")
JLLWrappers.@declare_file_product(libcutest_single_a)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libcutest_double,
        "lib/libcutest_double.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libcutest_double_a,
        "lib/libcutest_double.a",
    )

    JLLWrappers.@init_library_product(
        libcutest_single,
        "lib/libcutest_single.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libcutest_single_a,
        "lib/libcutest_single.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
