# Autogenerated wrapper script for CUTEst_jll for x86_64-w64-mingw32-libgfortran5
export libcutest_double, libcutest_double_a, libcutest_single, libcutest_single_a

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("CUTEst")
JLLWrappers.@declare_library_product(libcutest_double, "libcutest_double.dll")
JLLWrappers.@declare_file_product(libcutest_double_a)
JLLWrappers.@declare_library_product(libcutest_single, "libcutest_single.dll")
JLLWrappers.@declare_file_product(libcutest_single_a)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libcutest_double,
        "bin\\libcutest_double.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libcutest_double_a,
        "lib\\libcutest_double.a",
    )

    JLLWrappers.@init_library_product(
        libcutest_single,
        "bin\\libcutest_single.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libcutest_single_a,
        "lib\\libcutest_single.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
